name: Test on Paper 1.14.2 JDK 8

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run build:dist --if-present
        env:
          CI: true
      - name: Run the tests in Docker
        run: docker build . --file __tests__/Dockerfile --build-arg image_tag=paper-1.14.2-jdk8 --tag magikcraft:$(date +%s)
